### ISSUE TITLE
Answer to question on IRC

### ISSUE THREAD

**Issue by alcohol** [daslicht/ratchet-hello-world#1]
```
14:13:59           --> | daslicht (~daslicht@...) has joined #composer
14:15:56      daslicht | why is the import failing here : 
14:15:57      daslicht | https://github.com/daslicht/ratchet-hello-world
14:15:59      daslicht | ?
```

It is failing because you load `vendor/autoload.php` after the `use MyApp\Chat;` statement (the autoloader should be required before anything else).

Also, I highly recommend you add a `.gitignore` to your repository with the following content:

```
# .gitignore
.idea/
vendor/
```

**Comment by daslicht** [comment]
Thank you , just saw the answer !
Do you mean like this ?

https://github.com/daslicht/ratchet-hello-world/blob/master/bin/chat-server.php#L2

**Comment by daslicht** [comment]
I will retry it again as far as I get a timeslot for it

**Comment by alcohol** [comment]
Actually I don't think it should make any difference. Also, the code works for me locally.

**Comment by daslicht** [comment]
thats strange

**Comment by daslicht** [comment]
I just re-cloned it inclusive the change, and indeed i get no error anymore.
Interesting , so the imports order is important.

**Comment by daslicht** [comment]
Looks like the documentation should be updated to reflect that the order is important : 

http://socketo.me/docs/hello-world

**Comment by alcohol** [comment]
No the order is not important. It works for me both ways.

**Comment by daslicht** [comment]
you are correct its working now as well , ?! 
Looks like there must be changed something on my computer since my last try.
